### ISSUE TITLE
PMP/PMA test

### ISSUE THREAD

**Issue by panda1628** [riscv/riscv-arch-test#156]
Is there any PMP/PMA compliance test?

**Comment by allenjbaum** [comment]
no, not yet. There are some older tests in the riscv-test directory, but
those aren't official, and I don't think coverage is up to what we intend
to test.

**Comment by allenjbaum** [comment]
Oh, and PMAs are very specific to every implementation, so it isn't clear
how we could possibly test them.

**Comment by panda1628** [comment]
Can you please give me the path? 
"There are some older tests in the riscv-test directory"

I am looking for an example of PMP/PMA test, thanks

**Comment by pdonahue-ventana** [comment]
https://github.com/riscv/riscv-tests/blob/master/benchmarks/pmp/pmp.c

**Comment by allenjbaum** [comment]
Note that these older tests are self checking, and don't conform to the test format spec, so can't be run with the architectural test framework.

**Comment by allenjbaum** [comment]
question answered, I'm closing this issue
