### ISSUE TITLE
merge of new K crypto scalar tests

### ISSUE THREAD

**Issue by Imperas** [riscv/riscv-arch-test#173]
Can somebody please complete this pull request and merge it.
thanks
https://github.com/riscv/riscv-arch-test/pull/172

**Comment by allenjbaum** [comment]
Just to make sure you know this isn't being ignored: it is being reviewed,
and there are minor issues that appear to need minor fixes. Nothing
major, which probably is no surprise.
We are surprised that some of the tests, at least, have exactly the same
test vectors for all but 3 or 4 of 145 test cases. That's an
interesting result of the test methodology

**Comment by Imperas** [comment]
All issues resolved now and approved - so I will close this issue when the merge is completed.
