### ISSUE TITLE
Global linker script is not appropriate

### ISSUE THREAD

**Issue by jeremybennett** [riscv/riscv-arch-test#63]
We have a handful of linker scripts, in `riscv-test-env/{p,pm,pt,v}/link.ld`. These impose certain views on section naming and memory maps. These really are target platform specific details, and so should be configured on a per platform basis. Otherwise we'll be adding a new version for every platform to be tested.

**Comment by eroom1966** [comment]
@jeremybennett 
What is your proposed fix?
for a physical platform - there is a real physical constraint, and in fact for ibex, you will see I did create a platform specific linker script
For simulators however, these can be any shape we wish, so there is no real restriction, just a common description for the linker memory layout and the simulation setup

**Comment by jeremybennett** [comment]
I was really just suggesting they should be in the target specific directory, not centrally.

**Comment by allenjbaum** [comment]
Can those environments be easily overridden? 
Where is the platform specific ibex script? 
Does that solution work for everyone (without breaking anything)?

**Comment by neelgala** [comment]
This is requirement has been fixed in RISCOF. Each target provides their own linker scripts to the framework. A sample linker script is also provided by the initial setup command.

**Comment by allenjbaum** [comment]
This has been fixed pre-riscof, I believe.

**Comment by neelgala** [comment]
yes. can be closed. Open if issue still persists.
