### ISSUE TITLE
RV_COMPLIANCE_HALT must contain SWSIG

### ISSUE THREAD

**Issue by bobbl** [riscv/riscv-arch-test#78]
I had some problems when porting the compliance tests to my RISC-V implementation. Finally, I understand the (in my opinion) weired interaction of macros. In this post I discribe the problems I faced and what I would change to simplify the structure and increase portability.

After porting `RV_COMPLIANCE_HALT`, half of the tests passed and half failed. The failing tests are the old tests that were imported from `riscv-tests`. The newer tests, explicitly written for `riscv-compliance` all passed.

The signature of the failing tests all differ only in the first word: it should be 1 but it was -1. The reason for that is that in most ports `RV_COMPLIANCE_HALT` maps to `RVTEST_PASS` which in turn uses `SWSIG` to write 1 to the first word of the signature. My implementation of `RV_COMPLIANCE_HALT` did not include `RVTEST_PASS` nor `SWSIG` and therefore did not write the 1.

However, the reference signatures of the newer tests do not start with a 1, because the correct value of the first word matters. How is that implemented? The old and the new tests differ in an include file. While the old tests include `aw_test_macros.h`, the newer tests include `riscv_test_macros.h` or
`test_macros.h`. The former defines `SWSIG` to write to the signature, while the latter define `SWSIG` as empty.

Consequently, including `SWSIG` in my definition of `RV_COMPLIANCE_HALT` solved the problem. However, I think that is a dirty solution because it breaks the independence between test suite, test environment and target. It adds a requirement to the implementation of `RV_COMPLIANCE_HALT` that should at least be documented. Even better this dependency should be removed, which can be done by the following modification:

Remove `SWSIG` from `RVTEST_PASS` and move it to `TEST_PASSFAIL`. That works, since the new tests are terminated by `RV_COMPLIANCE_HALT` (without. `SWSIG`), while the old test are terminated by `TEST_PASSFAIL` (with `SWSIG`), which in turn calls `RV_COMPLIANCE_HALT`. The empty `SWSIG` definitions in `riscv_test_macros.h` and `test_macros.h` can be removed.

When testing this modification, I found another (related) bug: `TEST_PASSFAIL` writes 1 to the first word, no matter if the test passed or failed. However, the definitions of `RVTEST_PASS` and `RVTEST_FAIL` imply that in the case of an error, the failing test number should be written. Therefore I propose to copy the code from these two macros to `TEST_PASSFAIL` (the labels are more important than the `bne`):

    #define TEST_PASSFAIL               \
            bne x0, TESTNUM, pass;      \
    fail:                               \
            sll TESTNUM, TESTNUM, 1;    \
            or TESTNUM, TESTNUM, 1;     \
            j 1f;                       \
    pass:                               \
            li TESTNUM, 1;              \
    1:                                  \
            RVTEST_SYNC;                \
            SWSIG (0, TESTNUM);         \
            RV_COMPLIANCE_HALT          \

I tested the modifications in my local repo. So, when the modifications are accepted, I can provide a pull request.

**Comment by neelgala** [comment]
You are right that some of the older tests will fail and thus need to be deprecated. This is being discussed and should be resolved soon.

the new test-format spec has an update on the macros and the next version indeed has a cleaner implementation and usage of the macros, thereby avoiding the issues you mentioned above. I would suggest waiting for the next revision to see if the issue still persists
